### ISSUE TITLE
Gitlab support

### ISSUE THREAD

**Issue by BrunnerLivio** [orta/danger-plugin-spellcheck#29]
Currently, this project does not seem to support Gitlab, due to the Github references in the code.
This leads to the following error:

```
Error:  TypeError: Cannot read property 'thisPR' of 
    at getPRParams (/builds/livio.brunner.lb1/stranger-danger/node_modules/danger-plugin-spellcheck/dist/index.js:44:62)
    at Object.<anonymous> (/builds/livio.brunner.lb1/stranger-danger/node_modules/danger-plugin-spellcheck/dist/index.js:93:20)
    at Generator.next (<anonymous>)
    at /builds/livio.brunner.lb1/stranger-danger/node_modules/danger-plugin-spellcheck/dist/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/builds/livio.brunner.lb1/stranger-danger/node_modules/danger-plugin-spellcheck/dist/index.js:3:12)
    at Object.exports.getSpellcheckSettings (/builds/livio.brunner.lb1/stranger-danger/node_modules/danger-plugin-spellcheck/dist/index.js:82:46)
    at /builds/livio.brunner.lb1/stranger-danger/node_modules/danger-plugin-spellcheck/dist/index.js:112:40
    at Generator.next (<anonymous>)
    at /builds/livio.brunner.lb1/stranger-danger/node_modules/danger-plugin-spellcheck/dist/index.js:7:71

````

**Comment by BrunnerLivio** [comment]
Would you be interested in such a support within this project? If so, would love to create a pull request for it!

**Comment by orta** [comment]
Sure, I'm open for it 👍🏻

**Comment by barryib** [comment]
@BrunnerLivio Is there any move on this ?

**Comment by BrunnerLivio** [comment]
@barryib I started with it but my focus has changed. I just remember that it‘s more difficult than anticipated because Gitlab/Github endpoints are quite different in a lot of cases. Since this project was not built in mind of supporting multiple platforms, it would require quite some refactoring.

Though it‘s basically open for anyone else to take this one up. Not quite sure whether I‘ll be able to come back to this any time soon.

One recommendation for someone taking on this: I‘d recommend creating an abstraction layer for the Github/Gitlab endpoints, so that you could easily support e.g. Bitbucket in the future

**Comment by glensc** [comment]
What would be the abstract word for pull request? gitlab has merge request.

**Comment by glensc** [comment]
Started something:
- https://github.com/orta/danger-plugin-spellcheck/pull/34

**Comment by orta** [comment]
"Code Changes" as an alternative?

**Comment by jayeshanandani** [comment]
Any update on this?
